# Generated by Django 3.1.5 on 2021-01-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210113_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image4',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, upload_to='category'),
        ),
    ]
